"""Map agent-harness hook payloads onto the canonical Action schema.

Each harness (Claude Code, Cursor, Kiro) delivers a pre-tool-use hook
payload on stdin in a slightly different envelope. This module normalises
the tool name + ``tool_input`` fields (command / file_path / content / MCP
args) into a single :class:`guard.schema.Action` that the deterministic
rule engine can evaluate, and provides the generated adapter-script text
used by ``agent-action-guard hooks install``.
"""

from __future__ import annotations

from typing import Any

from guard.schema import Action

__all__ = ["TARGETS", "adapter_script", "from_tool_input", "make_action"]

TARGETS = ("claude-code", "cursor", "kiro")


def _first(mapping: dict[str, Any], *keys: str) -> Any:
    for key in keys:
        value = mapping.get(key)
        if value is not None:
            return value
    return None


def _extract(payload: dict[str, Any]) -> tuple[str | None, dict[str, Any], str]:
    """Return ``(tool_name, tool_input, cwd)`` from a harness hook payload.

    Handles both the flat Claude-Code-style envelope (top-level ``tool_name``
    / ``tool_input``) and the nested Cursor/Kiro-style envelope where the
    relevant fields live under an ``event`` object.
    """
    event = payload.get("event")
    if isinstance(event, dict):
        tool_name = event.get("tool_name") or payload.get("tool_name")
        tool_input = event.get("tool_input") or payload.get("tool_input")
        cwd = event.get("cwd") or _first(payload, "cwd", "cwd_path", "working_dir") or "."
    else:
        tool_name = payload.get("tool_name")
        tool_input = payload.get("tool_input")
        cwd = _first(payload, "cwd", "cwd_path", "working_dir") or "."
    if not isinstance(tool_input, dict):
        tool_input = {}
    return tool_name, tool_input, cwd


def from_tool_input(
    tool_name: str | None,
    tool_input: dict[str, Any],
    cwd: str = ".",
) -> Action:
    """Map a normalised ``(tool_name, tool_input)`` pair onto an Action."""
    name = (tool_name or "").lower()
    ti = tool_input

    def get(*keys: str) -> Any:
        return _first(ti, *keys)

    shell_markers = ("shell", "bash", "command", "terminal", "exec")
    if any(marker in name for marker in shell_markers):
        return Action(
            type="shell",
            command=get("command", "cmd", "code"),
            cwd=cwd,
            source=tool_name,
        )
    # MCP tools are prefixed (e.g. mcp__filesystem__write_file) and may
    # otherwise collide with the file-write markers below, so check first.
    if any(marker in name for marker in ("mcp", "tool", "invoke")):
        return Action(type="mcp", tool=name, tool_args=ti, cwd=cwd, source=tool_name)
    if any(marker in name for marker in ("fs_write", "file_write", "write", "edit")):
        return Action(
            type="file",
            path=get("file_path", "path", "filename"),
            tool=name,
            tool_args=ti,
            cwd=cwd,
            source=tool_name,
        )
    if any(marker in name for marker in ("fs_read", "read_file", "read")):
        return Action(
            type="file",
            path=get("file_path", "path"),
            tool=name,
            cwd=cwd,
            source=tool_name,
        )
    if any(marker in name for marker in ("fetch", "http", "web", "url", "network", "request")):
        return Action(
            type="network",
            url=get("url", "uri"),
            method=get("method", "GET"),
            cwd=cwd,
            source=tool_name,
        )
    if "git" in name:
        return Action(
            type="git",
            command=get("command"),
            tool=name,
            cwd=cwd,
            source=tool_name,
        )
    # Fallback: a generic tool that still carries an executable command.
    return Action(
        type="shell",
        command=get("command"),
        tool=name,
        tool_args=ti,
        cwd=cwd,
        source=tool_name,
    )


def make_action(target: str, payload: dict[str, Any]) -> Action:
    """Build the canonical Action for a hook payload, regardless of envelope.

    ``target`` is accepted for forward-compatibility with per-harness
    quirks; the shared ``_extract`` + ``from_tool_input`` pipeline already
    handles all three current harnesses.
    """
    del target
    tool_name, tool_input, cwd = _extract(payload)
    return from_tool_input(tool_name, tool_input, cwd=cwd)


_SCRIPT_TEMPLATE = r'''#!/usr/bin/env python3
"""agent-action-guard pre-tool-use adapter for __TARGET__.

Reads a hook payload on stdin, maps it to an Action, evaluates it locally
(or against AGENT_ACTION_GUARD_URL /check), and emits the harness-native
deny signal when the action is blocked. Generated by
``agent-action-guard hooks install --target __TARGET__``.
"""

from __future__ import annotations

import json
import os
import sys
from typing import Any

from guard import evaluate_with_allowlist
from guard.adapters import make_action

TARGET = "__TARGET__"
DEFAULT_URL = __DEFAULT_URL__


def _resolve(payload: dict[str, Any]) -> tuple[str, str]:
    action = make_action(TARGET, payload)
    url = os.environ.get("AGENT_ACTION_GUARD_URL", "") or DEFAULT_URL
    if url:
        import urllib.request

        body = json.dumps(action.model_dump(mode="json")).encode("utf-8")
        req = urllib.request.Request(
            url.rstrip("/") + "/check",
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=5) as resp:
            result = json.loads(resp.read().decode("utf-8"))
        return str(result.get("verdict", "allow")), str(result.get("reason", ""))
    decision = evaluate_with_allowlist(action, None, use_classifier=True)
    return decision.verdict, decision.reason


def _deny(reason: str) -> int:
    """Emit the harness-native deny signal for the configured target."""
    if TARGET == "kiro":
        sys.stderr.write("agent-action-guard blocked action: " + reason + "\n")
        return 2
    payload: dict[str, Any] = {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }
    }
    sys.stdout.write(json.dumps(payload) + "\n")
    return 0


def main() -> int:
    try:
        payload = json.loads(sys.stdin.read() or "{}")
    except json.JSONDecodeError:
        return 0
    if not isinstance(payload, dict):
        return 0
    try:
        verdict, reason = _resolve(payload)
    except Exception:
        # Fail-open: never break the agent because the guard itself errored.
        return 0
    if verdict == "block":
        return _deny(reason)
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def adapter_script(target: str, *, default_url: str = "") -> str:
    """Return the runnable adapter-script text for a harness target."""
    if target not in TARGETS:
        raise ValueError(f"unknown target: {target!r}; expected one of {TARGETS}")
    import json as _json

    script = _SCRIPT_TEMPLATE.replace("__TARGET__", target)
    return script.replace("__DEFAULT_URL__", _json.dumps(default_url))
