#!/usr/bin/env python3
"""agent-action-guard pre-tool-use adapter for cursor.

Reads a hook payload on stdin, maps it to an Action, evaluates it locally
(or against AGENT_ACTION_GUARD_URL /check), and emits the harness-native
deny signal when the action is blocked. Generated by
``agent-action-guard hooks install --target cursor``.
"""

from __future__ import annotations

import json
import os
import sys
from typing import Any

from guard import evaluate_with_allowlist
from guard.adapters import make_action

TARGET = "cursor"
DEFAULT_URL = ""


def _resolve(payload: dict[str, Any]) -> tuple[str, str]:
    action = make_action(TARGET, payload)
    url = os.environ.get("AGENT_ACTION_GUARD_URL", "") or DEFAULT_URL
    if url:
        import urllib.request

        body = json.dumps(action.model_dump(mode="json")).encode("utf-8")
        req = urllib.request.Request(
            url.rstrip("/") + "/check",
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=5) as resp:
            result = json.loads(resp.read().decode("utf-8"))
        return str(result.get("verdict", "allow")), str(result.get("reason", ""))
    decision = evaluate_with_allowlist(action, None, use_classifier=True)
    return decision.verdict, decision.reason


def _deny(reason: str) -> int:
    """Emit the harness-native deny signal for the configured target."""
    if TARGET == "kiro":
        sys.stderr.write("agent-action-guard blocked action: " + reason + "\n")
        return 2
    payload: dict[str, Any] = {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }
    }
    sys.stdout.write(json.dumps(payload) + "\n")
    return 0


def main() -> int:
    try:
        payload = json.loads(sys.stdin.read() or "{}")
    except json.JSONDecodeError:
        return 0
    if not isinstance(payload, dict):
        return 0
    try:
        verdict, reason = _resolve(payload)
    except Exception:
        # Fail-open: never break the agent because the guard itself errored.
        return 0
    if verdict == "block":
        return _deny(reason)
    return 0


if __name__ == "__main__":
    sys.exit(main())
